"""Add day_of_week column to Schedule

Revision ID: 3a81e0f7e5d6
Revises: 
Create Date: 2025-04-18 14:01:22.433132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a81e0f7e5d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('time_with_child')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_with_child', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
